### ISSUE TITLE
Periodic issue with headers already being sent

### ISSUE THREAD

**Issue by kyle-mccarthy** [kyle-mccarthy/nest-next-starter#2]
This is an intermediate issue that occurs only during development.  It seems like next-server tries to set the headers on the response after it has already been set.  This can likely just be logged and ignored but right now it results in an unhandled promise rejection warning. 

```
(node:30757) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at DevServer._callee14$ (/Users/kylemccarthy/.../node_modules/next/dist/server/next-server.js:669:21)
    at tryCatch (/Users/kylemccarthy/.../node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/kylemccarthy/.../node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/kylemccarthy/.../node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Users/kylemccarthy/.../node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/kylemccarthy/.../node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at /Users/kylemccarthy/.../node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:34:7
    at new Promise (<anonymous>)
    at new F (/Users/kylemccarthy/.../node_modules/core-js/library/modules/_export.js:36:28)
    at DevServer.<anonymous> (/Users/kylemccarthy/.../node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:23:12)
    at DevServer.render404 (/Users/kylemccarthy/.../node_modules/next/dist/server/next-server.js:681:25)
    at DevServer._callee15$ (/Users/kylemccarthy/.../node_modules/next/dist/server/next-server.js:718:22)
    at tryCatch (/Users/kylemccarthy/.../node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/kylemccarthy/.../node_modules/regenerator-runtime/runtime.js:288:22)
```

**Comment by kyle-mccarthy** [comment]
This seems to be resolved in the actual package, and may have been related to nodemon attempted to reload updated components and HMR trying to do a hot reload at the same time.  This was only happening in development.  To resolve this I removed nodemon watching the components directory.
